name: Build

on:
  push:
    branches: ["master", "next"]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '14.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install jupyterlab~=2.0
    - name: Build the extension
      run: |
        jlpm
        jlpm run eslint:check
        # jlpm run test

        pip install .[test]
        python -m pytest

        jupyter lab build
        jupyter serverextension list 2>&1 | grep -ie "jupyterlab_pullrequests.*OK"
        jupyter labextension list 2>&1 | grep -ie "@jupyterlab/pullrequests.*OK"

        python -m jupyterlab.browser_check
